android_library(
  name = 'intent',
  srcs = glob(['*.java']),
  deps = [
    '//third_party/java/gson:gson',
    '//third_party/java/guava:guava',
    '//third_party/java/jsr305:jsr305',
  ],
  visibility = [ 'PUBLIC' ],
)

project_config(
  src_target = ':intent',
)
